# Generated by Django 3.0.5 on 2020-04-19 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200419_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='ID',
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
