# Generated by Django 3.0.5 on 2020-04-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20200419_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='numberOfPersonalizatios',
            new_name='personalizations',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='numberOfTests',
            new_name='tests',
        ),
    ]
