# Generated by Django 3.0.5 on 2020-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20200419_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='hasScript',
            field=models.BooleanField(default=False),
        ),
    ]
