# Generated by Django 3.0.5 on 2020-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_site_hasscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='hasScript',
            field=models.BooleanField(default=False, verbose_name='Script Installed'),
        ),
    ]
