# Generated by Django 3.0.5 on 2020-04-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20200419_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='personalizations',
            field=models.PositiveIntegerField(default=0, verbose_name='Personalizations'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tests',
            field=models.PositiveIntegerField(default=0, verbose_name='Tests'),
        ),
    ]
