# Generated by Django 3.0.5 on 2020-04-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='status',
            field=models.CharField(choices=[('blocked', 'Locked'), ('enabled', 'On'), ('disabled', 'Off')], default='on', max_length=20),
        ),
    ]
