# Generated by Django 3.0.5 on 2020-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20200419_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('blocked', 'blocked'), ('enable', 'enable'), ('disable', 'disable')], default='on', max_length=20),
        ),
    ]
